name: Build ROCK

on:
  workflow_call:

jobs:
  build-rock:
    runs-on: ubuntu-22.04
    steps:
    - name: Build rock
      uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v22.0.0
