name: Protected Branches

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: '0 8 * * 2'

concurrency:
    group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
    cancel-in-progress: true

permissions:
  contents: read
  packages: write
  security-events: write

jobs:

  build:
    strategy:
      matrix:
        arch:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: [self-hosted, linux, ARM64, medium, jammy]
          - arch: s390x
            runner: [self-hosted-linux-s390x-noble-medium]
    uses: canonical/identity-credentials-workflows/.github/workflows/rock-build.yaml@v3.1.2
    with:
      path: .
      arch: ${{ matrix.arch.arch }}
      runner: ${{ toJson(matrix.arch.runner) }}

  scan:
    needs: build
    uses: canonical/identity-credentials-workflows/.github/workflows/rock-scan.yaml@v3.1.2
    with:
      artifacts-key: ${{ github.sha }}-build-amd64
      arch: amd64
      path: .

  integration-tests:
    needs: build
    uses: ./.github/workflows/integration-tests.yaml

  publish:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'release-')
    needs: [scan, build, integration-tests]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to the Container registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rockcraft
        run: |
          sudo snap install rockcraft --classic --channel edge

      - uses: actions/download-artifact@v8
        with:
          name: ${{ github.sha }}-build-amd64

      - uses: actions/download-artifact@v8
        with:
          name: ${{ github.sha }}-build-arm64

      - uses: actions/download-artifact@v8
        with:
          name: ${{ github.sha }}-build-s390x

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(cat version/VERSION)"

          for arch in amd64 arm64 s390x; do
            rock_file=$(ls *_${arch}.rock | tail -n 1)
            sudo rockcraft.skopeo \
              --insecure-policy \
              copy \
              oci-archive:"${rock_file}" \
              docker-daemon:"ghcr.io/canonical/${image_name}:${version}-${arch}"
            docker push ghcr.io/canonical/${image_name}:${version}-${arch}
          done

          docker manifest create ghcr.io/canonical/${image_name}:${version} \
            ghcr.io/canonical/${image_name}:${version}-amd64 \
            ghcr.io/canonical/${image_name}:${version}-arm64 \
            ghcr.io/canonical/${image_name}:${version}-s390x
          docker manifest push ghcr.io/canonical/${image_name}:${version}

          docker manifest create ghcr.io/canonical/${image_name}:latest \
            ghcr.io/canonical/${image_name}:${version}-amd64 \
            ghcr.io/canonical/${image_name}:${version}-arm64 \
            ghcr.io/canonical/${image_name}:${version}-s390x
          docker manifest push ghcr.io/canonical/${image_name}:latest
