name: Main

on:
  push:
  schedule:
    - cron: '0 8 * * 2'

jobs:

  build:
    uses: ./.github/workflows/build-rock.yaml

  scan:
    needs: build
    uses: ./.github/workflows/scan-rock.yaml

  integration-tests:
    needs: build
    uses: ./.github/workflows/integration-tests.yaml

  publish:
#    if: github.ref_name == 'main'
    needs: [scan, build, integration-tests]
    uses: ./.github/workflows/publish-rock.yaml
