name: Publish ROCK

on:
  workflow_call:

jobs:
  publish-rock:
    name: Publish rock
    uses: canonical/data-platform-workflows/.github/workflows/release_rock.yaml@v22.0.0
    with:
      artifact-prefix: ${{ needs.go-build.outputs.artifact-prefix }}
    permissions:
      packages: write
      contents: write